components:
  PreProcessor:
    module: app.detector.components
    init:
      scale: static.config.preprocessor_config.scale
      size: static.config.preprocessor_config.size
      mean: static.config.preprocessor_config.mean
      swapRB: static.config.preprocessor_config.swapRB
      crop: static.config.preprocessor_config.crop
    input:
      _image: dynamic.image
    output:
      _blob: dynamic.blob
  ObjectDetector:
    module: app.detector.components
    init:
      model: static.model
    input:
      _blob: dynamic.blob
    output:
      _outs: dynamic.outs
      _max_confidence: dynamic.max_confidence
  EventSender:
    module: app.detector.components
    init:
      broker: static.broker
      threshold: static.config.event_sender_config.threshold
    input:
      _timestamp: dynamic.timestamp
      _image: dynamic.image
      _outs: dynamic.outs
      _max_confidence: dynamic.max_confidence